"use strict";Object.defineProperty(exports, "__esModule", { value: true });var _createClass = function () {function defineProperties(target, props) {for (var i = 0; i < props.length; i++) {var descriptor = props[i];descriptor.enumerable = descriptor.enumerable || false;descriptor.configurable = true;if ("value" in descriptor) descriptor.writable = true;Object.defineProperty(target, descriptor.key, descriptor);}}return function (Constructor, protoProps, staticProps) {if (protoProps) defineProperties(Constructor.prototype, protoProps);if (staticProps) defineProperties(Constructor, staticProps);return Constructor;};}();var _get = function get(object, property, receiver) {if (object === null) object = Function.prototype;var desc = Object.getOwnPropertyDescriptor(object, property);if (desc === undefined) {var parent = Object.getPrototypeOf(object);if (parent === null) {return undefined;} else {return get(parent, property, receiver);}} else if ("value" in desc) {return desc.value;} else {var getter = desc.get;if (getter === undefined) {return undefined;}return getter.call(receiver);}};var _react = require("react");var _react2 = _interopRequireDefault(_react);
var _reactstrap = require("reactstrap");
var _ValidationComponent2 = require("../validation/ValidationComponent");var _ValidationComponent3 = _interopRequireDefault(_ValidationComponent2);
var _FaIcon = require("../faicon/FaIcon");var _FaIcon2 = _interopRequireDefault(_FaIcon);function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { default: obj };}function _classCallCheck(instance, Constructor) {if (!(instance instanceof Constructor)) {throw new TypeError("Cannot call a class as a function");}}function _possibleConstructorReturn(self, call) {if (!self) {throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return call && (typeof call === "object" || typeof call === "function") ? call : self;}function _inherits(subClass, superClass) {if (typeof superClass !== "function" && superClass !== null) {throw new TypeError("Super expression must either be null or a function, not " + typeof superClass);}subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } });if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;}


/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * CheckInput is an input element to provide checked given item or items.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @class CheckInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @extends {ValidationComponent}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */var
CheckInput = function (_ValidationComponent) {_inherits(CheckInput, _ValidationComponent);























































































    /**
                                                                                            *
                                                                                            * @param {Object} props
                                                                                            */ /**
                                                                                                * propTypes
                                                                                                * @static
                                                                                                */function CheckInput(props) {_classCallCheck(this, CheckInput);var _this = _possibleConstructorReturn(this, (CheckInput.__proto__ || Object.getPrototypeOf(CheckInput)).call(this, props));_this.





























































































        isChecked = function (value) {
            if (typeof value !== "undefined") {
                return _this._hasMultiItem ?
                _this._value.indexOf(value) !== -1 : _this._value;
            }
            return _this._hasMultiItem ? _this._value.length > 0 : _this._value;
        };_this._hasMultiItem = !!_this.props.items;_this._value = _this.props.value;if (!_this._value) {_this._value = _this._hasMultiItem ? [] : false;}return _this;} /**
                                                                                                                                                                          *
                                                                                                                                                                          * render
                                                                                                                                                                          * @returns {string}
                                                                                                                                                                          **/ /**
                                                                                                                                                                               * defaultProps
                                                                                                                                                                               * @static
                                                                                                                                                                               */_createClass(CheckInput, [{ key: "render", value: function render() {var label = this.props.label === undefined ? undefined : _react2.default.createElement(_reactstrap.Label, null, " ", this.props.label, " ");return _get(CheckInput.prototype.__proto__ || Object.getPrototypeOf(CheckInput.prototype), "wrapComponent", this).call(this, _react2.default.createElement(_reactstrap.FormGroup, { hidden: this.props.hidden }, label, _react2.default.createElement("div", { className: this.props.formControl ? "form-control" : "", style: { height: "auto" } }, this._hasMultiItem ? this.__createCheckInputs(this.props.items) : this.__createCheckInput(this.props.item))));} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * create Check Input items from given items.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * @param items
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * @returns {Array}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * @private
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */ }, { key: "__createCheckInputs", value: function __createCheckInputs(items) {var components = [];if (items) {for (var i = 0; i < items.length; i++) {components.push(this.__createCheckInput(items[i]));}}return components;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * create a CheckInput from given item.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @param {Map} item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @returns {Object}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @private
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */ }, { key: "__createCheckInput", value: function __createCheckInput(item) {if (!item) {return "item cannot be undefined, please check your name";}var value = item[this.props.valueField];var text = item[this.props.textField];var isChecked = this.isChecked(value);var icon = isChecked ? " fa-check-square-o" : " fa-square-o";var disabled = isChecked ? "disabled-check-input" : "";var name = this.props.name ? this.props.name + "[]" : null;var input = isChecked ? _react2.default.createElement("input", { type: "hidden", value: value, name: name, disabled: !isChecked }) : null;var onClick = null;if (!this.props.disabled) {onClick = (this._hasMultiItem ? this.__onClickMulti : this.__onClickSingle).bind(this, value);}return _react2.default.createElement("div", { style: { cursor: "pointer" }, value: value, className: "checkbox " + disabled, onClick: onClick, key: value }, _react2.default.createElement("label", { htmlFor: name, style: { paddingLeft: "2px" } }, _react2.default.createElement(_FaIcon2.default, { code: icon + " state-icon", size: "fa-sm" })), " ", text, input);} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * This method has two difference calls.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 1 - call without parameter returns true if at least one of the values is checked.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 2 - call with key parameter returns true if the given key is in checked list.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * @param {string} value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * @returns {boolean}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */ }, { key: "getValue", /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * returns checked values as string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * @returns {string}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */value: function getValue() {return this._value;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * Internal onClick event for Single CheckInput. It is triggered every time.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * @return {boolean}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */ }, { key: "__onClickSingle", value: function __onClickSingle() {var value = !this._value;var result = this.__callOnChange(value, this._value);if (result) {this._value = value;}return result;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * Internal onClick event for Single CheckInput. It is triggered every time.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * @param {string} value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * @return {boolean}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */ }, { key: "__onClickMulti", value: function __onClickMulti(value) {var willChangeValue = this._value.slice(0);var ind = willChangeValue.indexOf(value);if (ind !== -1) {willChangeValue.splice(ind, 1);} else {ind = willChangeValue.push(value) - 1;}
            var result = this.__callOnChange(willChangeValue, this._value);
            if (result) {
                this._value = willChangeValue;
            }
            return result;
        }

        /**
           *
           * @param {any} value
           * @param {any} value
           * @returns {boolean}
           * @private
           */ }, { key: "__callOnChange", value: function __callOnChange(
        value, oldValue) {
            var result = true;
            if (this.props.onChange) {
                var e = {
                    target: {
                        value: value,
                        oldValue: oldValue,
                        parsedValue: value,
                        name: this.props.name } };


                result = this.props.onChange(e);
            }
            return result;
        } }, { key: "componentWillReceiveProps", value: function componentWillReceiveProps(

        nextProps) {
            this._value = nextProps.value;
            if (!this._value) {
                this._value = this._hasMultiItem ? [] : false;
            }
        } }]);return CheckInput;}(_ValidationComponent3.default);CheckInput.propTypes = { /**
                                                                                           * Style map for the component.
                                                                                           */style: _react2.default.PropTypes.object, /**
                                                                                                                                       * Label for the form control.
                                                                                                                                       */label: _react2.default.PropTypes.string, /**
                                                                                                                                                                                   * name use as input field name
                                                                                                                                                                                   */name: _react2.default.PropTypes.string, /**
                                                                                                                                                                                                                              * Array of items. All items will be rendered as separate checkbox input.
                                                                                                                                                                                                                              */items: _react2.default.PropTypes.array, /**
                                                                                                                                                                                                                                                                         * Item will be rendered checkbox input single.
                                                                                                                                                                                                                                                                         */item: _react2.default.PropTypes.object, /**
                                                                                                                                                                                                                                                                                                                    * Checked value or values
                                                                                                                                                                                                                                                                                                                    */value: _react2.default.PropTypes.oneOfType([_react2.default.PropTypes.bool, _react2.default.PropTypes.array]), /**
                                                                                                                                                                                                                                                                                                                                                                                                                                      * Key of map item which is defined in given array `items`
                                                                                                                                                                                                                                                                                                                                                                                                                                      */valueField: _react2.default.PropTypes.any, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * label of map item which is defined in given array `items`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */textField: _react2.default.PropTypes.string, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * onChange callback function when selection `item` or `items` changed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */onChange: _react2.default.PropTypes.func, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * Validations functions to validate value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */validations: _react2.default.PropTypes.object, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * Disable input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */disabled: _react2.default.PropTypes.bool, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * it specifies that an input field is read-only
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */readOnly: _react2.default.PropTypes.bool, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * it specifies that an input field is hidden or visible
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */hidden: _react2.default.PropTypes.bool, /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       *Defines the display style of the Validation message.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */validationDisplay: _react2.default.PropTypes.oneOf(["overlay", "block"]), /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * Defines class of the check input. (form-control or not)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */formControl: _react2.default.PropTypes.bool };CheckInput.defaultProps = { textField: "text", valueField: "value", disabled: false, readOnly: false, hidden: false, validationDisplay: "block", formControl: true };exports.default = CheckInput;